---
remote_theme: mmistakes/so-simple-theme
title: "Sherwood AI Data-Centre Referendum"
image:
  path: /images/DSCF7852.JPG
  #thumbnail: /images/referendum-thumb.jpg
  caption: "Photo credit: [Taran](https://www.instagram.com/itsblurrybud/)"
---
